# A sample Gemfile
source 'https://rubygems.org'

gem 'first_app', git: 'https://github.com/dieze/heroku-modular-first_app-back'
gem 'second_app', git: 'https://github.com/dieze/heroku-modular-second_app-back'
